// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package client

import (
	"encoding/json"
	"net/http"

	"github.com/openvcloud/ovc-controller-manager/client/goraml"
	"github.com/openvcloud/ovc-controller-manager/client/types"
)

type BlueprintsService service

// Execute a blueprint on the ZeroRobot
func (s *BlueprintsService) ExecuteBlueprint(body types.Blueprint, headers, queryParams map[string]interface{}) ([]types.Task, *http.Response, error) {
	var err error
	var respBody200 []types.Task

	resp, err := s.client.doReqWithBody("POST", s.client.BaseURI+"/blueprints", &body, headers, queryParams)
	if err != nil {
		return respBody200, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 200:
		err = json.NewDecoder(resp.Body).Decode(&respBody200)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody200, resp, err
}
