// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package client

import (
	"encoding/json"
	"net/http"

	"github.com/openvcloud/ovc-controller-manager/client/goraml"
	"github.com/openvcloud/ovc-controller-manager/client/types"
)

type TemplatesService service

// List all the templates available to the ZeroRobot
func (s *TemplatesService) ListTemplates(headers, queryParams map[string]interface{}) ([]types.Template, *http.Response, error) {
	var err error
	var respBody200 []types.Template

	resp, err := s.client.doReqNoBody("GET", s.client.BaseURI+"/templates", headers, queryParams)
	if err != nil {
		return respBody200, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 200:
		err = json.NewDecoder(resp.Body).Decode(&respBody200)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody200, resp, err
}

// Clone a template repository and make the templates available to the ZeroRobot
func (s *TemplatesService) AddTemplateRepo(body types.TemplateRepository, headers, queryParams map[string]interface{}) ([]types.Template, *http.Response, error) {
	var err error
	var respBody201 []types.Template

	resp, err := s.client.doReqWithBody("POST", s.client.BaseURI+"/templates", &body, headers, queryParams)
	if err != nil {
		return respBody201, nil, err
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case 201:
		err = json.NewDecoder(resp.Body).Decode(&respBody201)
	default:
		err = goraml.NewAPIError(resp, nil)
	}

	return respBody201, resp, err
}
