// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"encoding/json"
	"gopkg.in/validator.v2"
)

// A blueprint is a description of which service you want to create
// and what action you want to add to a task list.
type Blueprint struct {
	Content json.RawMessage `json:"content" validate:"nonzero"`
}

func (s Blueprint) Validate() error {

	return validator.Validate(s)
}
