// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

type EnumServiceStateState string

const (
	EnumServiceStateStateok      EnumServiceStateState = "ok"
	EnumServiceStateStateerror   EnumServiceStateState = "error"
	EnumServiceStateStatewarning EnumServiceStateState = "warning"
	EnumServiceStateStateskipped EnumServiceStateState = "skipped"
)
