// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

type EnumTaskState string

const (
	EnumTaskStatenew     EnumTaskState = "new"
	EnumTaskStateok      EnumTaskState = "ok"
	EnumTaskStaterunning EnumTaskState = "running"
	EnumTaskStateerror   EnumTaskState = "error"
)
