// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Error struct {
	Code        int    `json:"code" validate:"nonzero"`
	Message     string `json:"message" validate:"nonzero"`
	Stack_trace string `json:"stack_trace,omitempty"`
}

func (s Error) Validate() error {

	return validator.Validate(s)
}
