// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Service struct {
	Guid     string         `json:"guid" validate:"nonzero"`
	Name     string         `json:"name" validate:"nonzero"`
	Parent   string         `json:"parent,omitempty"`
	State    []ServiceState `json:"state" validate:"nonzero"`
	Template string         `json:"template" validate:"nonzero"`
	Version  string         `json:"version" validate:"nonzero"`
}

func (s Service) Validate() error {

	return validator.Validate(s)
}
