// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type ServiceState struct {
	Category string                `json:"category" validate:"nonzero"`
	State    EnumServiceStateState `json:"state" validate:"nonzero"`
	Tag      string                `json:"tag" validate:"nonzero"`
}

func (s ServiceState) Validate() error {

	return validator.Validate(s)
}
