// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type ServiceUpgradeRequest struct {
	Template string `json:"template" validate:"nonzero"`
}

func (s ServiceUpgradeRequest) Validate() error {

	return validator.Validate(s)
}
