// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

// Type return after a task is added to a task list
type Task struct {
	TaskCreate
	Created       int           `json:"created" validate:"nonzero"`
	Eco           Eco           `json:"eco,omitempty"`
	Guid          string        `json:"guid" validate:"nonzero"`
	Result        string        `json:"result,omitempty"`
	Service_guid  string        `json:"service_guid" validate:"nonzero"`
	Service_name  string        `json:"service_name" validate:"nonzero"`
	State         EnumTaskState `json:"state" validate:"nonzero"`
	Template_name string        `json:"template_name" validate:"nonzero"`
}

func (s Task) Validate() error {

	return validator.Validate(s)
}
