// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"encoding/json"
	"gopkg.in/validator.v2"
)

type TaskCreate struct {
	Action_name string          `json:"action_name" validate:"nonzero"`
	Args        json.RawMessage `json:"args,omitempty"`
}

func (s TaskCreate) Validate() error {

	return validator.Validate(s)
}
