// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type TemplateRepository struct {
	Branch string `json:"branch,omitempty"`
	Url    string `json:"url" validate:"nonzero"`
}

func (s TemplateRepository) Validate() error {

	return validator.Validate(s)
}
