// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package types

import (
	"gopkg.in/validator.v2"
)

type Template struct {
	Account    string `json:"account" validate:"nonzero"`
	Host       string `json:"host" validate:"nonzero"`
	Name       string `json:"name" validate:"nonzero"`
	Repository string `json:"repository" validate:"nonzero"`
	Uid        string `json:"uid" validate:"nonzero"`
	Version    string `json:"version" validate:"nonzero"`
}

func (s Template) Validate() error {

	return validator.Validate(s)
}
